// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCge6Net6qvmJcRz5tESH94OuIziHlju2A',
    appId: '1:941137475897:web:26cc886753fc2ae8e790e8',
    messagingSenderId: '941137475897',
    projectId: 'todolist-97d73',
    authDomain: 'todolist-97d73.firebaseapp.com',
    storageBucket: 'todolist-97d73.appspot.com',
    measurementId: 'G-J5RXKK8HPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZVkkQdNTdY4Q4erNNbyxTrWPe-BvumU',
    appId: '1:941137475897:android:d453084a87bf057fe790e8',
    messagingSenderId: '941137475897',
    projectId: 'todolist-97d73',
    storageBucket: 'todolist-97d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7PIO39nhlrce9DZCrtwYEUX4L_Z55LkE',
    appId: '1:941137475897:ios:1f26020f02bae032e790e8',
    messagingSenderId: '941137475897',
    projectId: 'todolist-97d73',
    storageBucket: 'todolist-97d73.appspot.com',
    iosBundleId: 'com.example.flutterTodoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7PIO39nhlrce9DZCrtwYEUX4L_Z55LkE',
    appId: '1:941137475897:ios:9a165250d466103ce790e8',
    messagingSenderId: '941137475897',
    projectId: 'todolist-97d73',
    storageBucket: 'todolist-97d73.appspot.com',
    iosBundleId: 'com.example.flutterTodoList.RunnerTests',
  );
}
